- godot/Main.gd
- godot/Main.tscn
- rust/decentraland-godot-lib/build.rs
- rust/decentraland-godot-lib/src/dcl/crdt/last_write_wins.rs
- rust/decentraland-godot-lib/src/dcl/crdt/message.rs
- rust/decentraland-godot-lib/src/dcl/crdt/mod.rs
- rust/decentraland-godot-lib/src/dcl/js/engine.rs
- rust/decentraland-godot-lib/src/dcl/serialization/crdt.rs
- rust/decentraland-godot-lib/src/dcl/serialization/mod.rs
- rust/decentraland-godot-lib/src/dcl/serialization/rust_data_types.rs
- rust/decentraland-godot-lib/src/dcl/serialization/writer.rs
- rust/decentraland-godot-lib/src/scene_runner/components/transform_and_parent.rs
- rust/decentraland-godot-lib/src/scene_runner/godot_dcl_scene.rs
- rust/decentraland-godot-lib/src/scene_runner/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/update_scene.rs
- Implement PUT and DELETE component from dirty
- Restore and add some tests
- Put camera transform in PLAYER and CAMERA entities to the scene
> feat: implement `PUT` and `DELETE` component and send to the scene

- rust/decentraland-godot-lib/src/godot_classes/dcl_ui_background.rs
> fix: promise resolving for fetching texture on ui background

- .github/workflows/ci.yml
- godot/.godot/global_script_class_cache.cfg
- godot/src/decentraland_components/avatar.gd
- godot/src/main.gd
- godot/src/tool/avatar_renderer/avatar_renderer_helper.gd
- godot/src/tool/avatar_renderer/avatar_renderer_standalone.gd
- godot/src/tool/avatar_renderer/avatar_renderer_standalone.tscn
- godot/src/ui/components/backpack/avatar_preview.tscn
- godot/src/ui/explorer.gd
Enable branching execution to something different as scene `explorer.tscn`.
In this case:
- `--avatar-renderer` enables avatar rendering execution, with a file `--avatars` like the example
You can run this in linux with:
`./decentraland.godot.client.x86_64 --rendering-driver opengl3 --avatar-renderer --avatars avatars.json`
```json
{
"baseUrl": "https://peer.decentraland.org/content",
"payload": [
{
"destPath": "./avatar.png",
"avatar": {
"bodyShape": "urn:decentraland:off-chain:base-avatars:BaseFemale",
"wearables": [
"urn:decentraland:off-chain:base-avatars:f_sweater",
"urn:decentraland:off-chain:base-avatars:f_jeans",
"urn:decentraland:off-chain:base-avatars:bun_shoes",
"urn:decentraland:off-chain:base-avatars:standard_hair",
"urn:decentraland:off-chain:base-avatars:f_eyes_01", …
```
> poc: create avatar renderer cli

- godot/src/logic/realm.gd
- godot/src/logic/scene_fetcher.gd
fix: await correctly load scene (now better debugging)
fix: accept scenes that doesn't have main script, only main.crdt
Simple fixes
> fix: city loader content server url

- godot/src/logic/scene_fetcher.gd
The dev version has a fix for the UVs for PlaneShapes to match the textures
> feat: change sdk7 adaptation layer to use the dev version

- rust/decentraland-godot-lib/src/auth/dcl_player_identity.rs
- rust/decentraland-godot-lib/src/auth/deploy_profile.rs
- rust/decentraland-godot-lib/src/avatars/avatar_scene.rs
- rust/decentraland-godot-lib/src/comms/profile.rs
- rust/decentraland-godot-lib/src/dcl/components/internal_player_data.rs
- rust/decentraland-godot-lib/src/dcl/components/mod.rs
- rust/decentraland-godot-lib/src/dcl/crdt/mod.rs
- rust/decentraland-godot-lib/src/dcl/js/events.rs
- rust/decentraland-godot-lib/src/dcl/js/players.rs
- rust/decentraland-godot-lib/src/dcl/serialization/internal_player_data.rs
- rust/decentraland-godot-lib/src/dcl/serialization/mod.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_avatar.rs
- rust/decentraland-godot-lib/src/scene_runner/components/avatar_data.rs
- rust/decentraland-godot-lib/src/scene_runner/scene.rs
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
- rust/decentraland-godot-lib/src/scene_runner/update_scene.rs
Observables `onEnterScene` and `onLeaveScene` had erractic behaviour.
Now the mechanism to define if the player is in/out of the scene is independent of the transform value.
Fix corner cases
> fix: defining when a player is inside a parcel scene or not

- godot/src/decentraland_components/mesh_renderer.gd
- rust/decentraland-godot-lib/src/scene_runner/components/mesh_collider.rs
- rust/decentraland-godot-lib/src/scene_runner/components/tween.rs
> implement face_direction(tween) and top/bottom to cylinder (mesh collider)

- godot/src/decentraland_components/avatar.gd
- godot/src/decentraland_components/wearables/wearables.gd
- godot/src/tool/avatar_renderer/test-input.json
- rust/decentraland-godot-lib/src/content/content_provider.rs
- rust/decentraland-godot-lib/src/dcl/common/mod.rs
- rust/decentraland-godot-lib/src/dcl/common/string.rs
Fixes https://github.com/decentraland/godot-explorer/issues/178
> fix: add hidings to skin category (adr-60) and ignore tokenId on wearable urns

- godot/src/decentraland_components/avatar_attach.gd
- godot/src/global.gd
- godot/src/ui/components/custom_slider/custom_background_slider.gd
- godot/src/ui/components/loading_screen/loading_screen_progress_logic.gd
- godot/src/ui/explorer.gd
- rust/decentraland-godot-lib/src/scene_runner/update_scene.rs
Fix #189 
Fix #190 
- Also fix some typos and godot warnings.
- Warning message when a scene takes more than 1/60.0 time
- Add `--force-mobile` param
> fix: start at 0,0 not loading and fix: loading screen never hides in empty parcels 

- godot/src/logic/content/dcl_urn.gd
- godot/src/logic/content/opensea_nft_fetcher.gd
- godot/src/ui/dialogs/nft_dialog.gd
- godot/src/ui/dialogs/nft_dialog.tscn
- rust/decentraland-godot-lib/src/content/content_provider.rs
- rust/decentraland-godot-lib/src/content/texture.rs
- rust/decentraland-godot-lib/src/lib.rs
- rust/decentraland-godot-lib/src/utils/infer_mime.rs
- rust/decentraland-godot-lib/src/utils/mod.rs
feat: add multiple image formats for fetch texture
> feat: opensea nft v2 and multiple image formats for fetch textures

- godot/src/logic/scene_fetcher.gd
Sometimes the target_position is an array with just one element, and it was not considered in the first iteration of the spawn points.
This PR fix that.
> fix: target position for spawn points

- godot/src/ui/components/discover/carrousel/discover_carrousel_item.tscn
- godot/src/ui/components/discover/discover.tscn
Fix https://github.com/decentraland/godot-explorer/issues/243
> feat: rounded corners in discover items

- godot/src/logic/player/player.gd
- godot/src/ui/components/pointer_tooltip/pointer_tooltip.gd
- godot/src/ui/components/pointer_tooltip/pointer_tooltip.tscn
- godot/src/ui/explorer.gd
- godot/src/ui/explorer.tscn
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
Fix https://github.com/decentraland/godot-explorer/issues/239
Now the mouse cursor moves to the place where to touch, and resets when you move the camara
> feat: mouse cursor moves on touch on mobile

- godot/src/decentraland_components/avatar/avatar.gd
- godot/src/decentraland_components/avatar/wearables/wearables.gd
> fix: after using the fallback wearables the eyes/mouth are unchangeable

- godot/src/logic/player/player_identity.gd
- godot/src/ui/components/auth/lobby.gd
- godot/src/ui/components/auth/lobby.tscn
- godot/src/ui/components/backpack/backpack.gd
- rust/decentraland-godot-lib/src/auth/dcl_player_identity.rs
- rust/decentraland-godot-lib/src/auth/deploy_profile.rs
- Backpack was not loaded with the correct Web3 Profile
- New fallback with guest_profile or default
- New loading stage when you're in the lobby
- Now the profile is directly deployed when the lobby ends
- The profile picture is generated after the lobby fix https://github.com/decentraland/godot-explorer/issues/268
- If you don't have name, you don't have a valid profile
> fix: improve profile change flow and generate profile image on first time

- rust/decentraland-godot-lib/src/scene_runner/components/pointer_events.rs
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
feat: add mesh name to the raycast result
Fix https://github.com/decentraland/godot-explorer/issues/293
Fix https://github.com/decentraland/godot-explorer/issues/63
Fix https://github.com/decentraland/godot-explorer/issues/359
> fix: pointer events, and add mesh name to the raycast result

- godot/src/ui/components/recording_notification/recording_notification.gd
- godot/src/ui/components/voice_chat_recorder/voice_chat_recorder.gd
- godot/src/ui/explorer.gd
- godot/src/ui/explorer.tscn
- rust/decentraland-godot-lib/src/comms/adapter/archipelago.rs
- rust/decentraland-godot-lib/src/comms/communication_manager.rs
- rust/xtask/src/run.rs
Fix https://github.com/decentraland/godot-explorer/issues/365
> fix: disable UI mic when needed

- godot/src/decentraland_components/avatar/avatar.gd
- godot/src/decentraland_components/avatar/avatar.tscn
- godot/src/test/avatar/avatar_list.json
- godot/src/test/avatar/avatar_tester_standalone.gd
- godot/src/test/avatar/avatar_tester_standalone.tscn
- rust/decentraland-godot-lib/src/avatars/item.rs
- rust/decentraland-godot-lib/src/dcl/common/wearable.rs
- rust/xtask/src/run.rs
> fix: some avatar has a bad-hiding of lower_body (and head stuffs)

- godot/src/decentraland_components/avatar_attach.gd
- godot/src/ui/components/auth/lobby.gd
Also fix guest generation, with generating first the wallet so the profile has the `userId` filled
> fix: beer-dispenser scene, avatar attach points not enabled

- rust/decentraland-godot-lib/src/test_runner/testing_tools.rs
It simplifies the math to follow 1-1 the specification: https://github.com/decentraland/protocol/pull/185
> chore: simplifies test formula

- .github/workflows/ci.yml
- README.md
MacOS last version of ffmpeg for brew was updated to @7, and for that reason it was failing in the CI
Also fix versions of ubuntu to avoid breaking changes
> fix: osx ci builds forcing ffmepg@6

- godot/src/decentraland_components/gltf_container.gd
- godot/src/decentraland_components/gltf_container.tscn
- godot/src/logic/scene_fetcher.gd
- rust/decentraland-godot-lib/src/dcl/js/fetch/mod.rs
- rust/decentraland-godot-lib/src/dcl/js/js_modules/main.js
- add gltf timeout (temp)
- add FIXED_LOCAL_ADAPTATION_LAYER for debugging purposes
- avoid breaking scene with unhandled catch promise
- add user-agent to fetch
> feat: add gltf timeout and user-agent 

- godot/src/decentraland_components/gltf_container.tscn
- rust/decentraland-godot-lib/src/dcl/js/fetch/mod.rs
- rust/decentraland-godot-lib/src/dcl/js/fetch/signed_fetch.rs
- rust/decentraland-godot-lib/src/dcl/js/websocket/mod.rs
- also add more info to debug ws
> fix: add headers to ws and signed-fetch, increase timeout

- godot/addons/resource_tracker/resource_tracker_debugger.gd
- godot/addons/resource_tracker/resource_tracker_panel.gd
- godot/addons/resource_tracker/resource_tracker_panel.tscn
- godot/src/decentraland_components/gltf_container.gd
- lib/src/content/content_provider.rs
- lib/src/godot_classes/dcl_resource_tracker.rs
lock resource in gltf containers between loading and instance collider
> fix: lock resource in gltf containers and track deleted content

- godot/src/ui/components/auth/lobby.gd
- godot/src/ui/components/auth/lobby.tscn
- godot/src/ui/components/auth/magic_login.gd
- godot/src/ui/explorer.gd
- lib/src/auth/dcl_player_identity.rs
- lib/src/auth/ephemeral_auth_chain.rs
fix: change open browser text when magic is not presented
> fix: check if auth chain is expired on restoring the session

- godot/src/ui/components/emotes/emote_wheel.gd
- godot/src/ui/explorer.gd
- godot/src/ui/explorer.tscn
Emotes were not being played after playing those in the Emote wheel.
Simple fix
> fix: emote player

- README.md
Just a small typo fix in README.md
> Update README.md - typo fix

- .github/workflows/android-build.yml
- .github/workflows/ci.yml
- godot/assets/environment/cli_environment.tres
- godot/src/decentraland_components/avatar/wearables/wearables.gd
- godot/src/test/avatar/avatar_list.json
- godot/src/test/avatar/avatar_tester_standalone.gd
fix eyebrow fallback
disable glow intensity
Previous
> temp: fix avatars

- .github/workflows/runner.yml
- entry-point.sh
- src/main.rs
> fix: docker build only in main, fix ci running multiple times on PRs and remove avatar tests from coverage

- godot/src/decentraland_components/avatar/wearables/wearables.gd
- godot/src/test/avatar/avatar_list.json
- godot/src/test/avatar/avatar_tester_standalone.gd
- godot/src/test/avatar/avatar_tester_standalone.tscn
- godot/src/tool/avatar_renderer/avatar_renderer_standalone.gd
- lib/src/dcl/js/mod.rs
cherry-pick fixes from bump-4.3
> fix: avatar rendering and scene crashes doesn't kill the scene anymore

- godot/src/global.gd
- godot/src/logic/scene_fetcher.gd
- godot/src/test/avatar/avatar_tester_standalone.gd
- godot/src/ui/components/debug_panel/debug_panel.gd
- godot/src/ui/components/debug_panel/debug_panel.tscn
- godot/src/ui/components/debug_panel/network_inspector/network_inspector_ui.gd
- godot/src/ui/components/debug_panel/network_inspector/network_inspector_ui.tscn
- godot/src/ui/components/debug_panel/network_inspector/request_entry.gd
- godot/src/ui/components/debug_panel/network_inspector/request_entry.tscn
- lib/Cargo.toml
- lib/android-build.sh
- lib/src/dcl/js/fetch/mod.rs
- lib/src/dcl/js/mod.rs
- lib/src/godot_classes/dcl_global.rs
- lib/src/http_request/http_queue_requester.rs
- lib/src/http_request/request_response.rs
- lib/src/tools/network_inspector.rs
- src/run.rs
Also:
- feat: limit scene fetch to 2 simultaneously
- fix: avatar fetched could be null
- chore: expose if there is JS debugging
- feat: add button to debug the current scene
- refactor: set enable_inspector as default feature and disable it for mobile
> feat: add network inspector UI

- godot/src/decentraland_components/gltf_container.gd
- godot/src/global.gd
- godot/src/logic/scene_fetcher.gd
- lib/src/content/content_provider.rs
- lib/src/content/resource_provider.rs
> feat: use asset optimized

- godot/src/config/config_data.gd
- godot/src/time.gd
- godot/src/ui/components/settings/settings.gd
- godot/src/ui/components/settings/settings.tscn
- lib/src/dcl/js/js_modules/Runtime.js
- lib/src/dcl/js/runtime.rs
- lib/src/godot_classes/dcl_global_time.rs
- lib/src/godot_classes/mod.rs
https://github.com/user-attachments/assets/d7147226-0585-48cb-97e7-563e002a6ef8
> feat: add world time
