- godot/.godot/global_script_class_cache.cfg
- godot/src/decentraland_components/audio_source.gd
- godot/src/decentraland_components/audio_source.tscn
- godot/src/decentraland_components/audio_streaming.gd
- godot/src/decentraland_components/avatar_attach.gd
- godot/src/decentraland_components/gltf_container.gd
- godot/src/decentraland_components/mesh_renderer.gd
- godot/src/global.gd
- godot/src/logic/content_manager.gd
- godot/src/logic/player/player.tscn
- godot/src/ui/explorer.gd
- godot/src/ui/voice_chat.gd
- rust/decentraland-godot-lib/src/godot_classes/audio_source.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_audio_source.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_camera_3d.rs
- rust/decentraland-godot-lib/src/godot_classes/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/components/audio_source.rs
- rust/decentraland-godot-lib/src/scene_runner/components/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/components/raycast.rs
- rust/decentraland-godot-lib/src/scene_runner/deleted_entities.rs
- rust/decentraland-godot-lib/src/scene_runner/scene.rs
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
- rust/decentraland-godot-lib/src/scene_runner/update_scene.rs
> feat: add audio source

- godot/src/decentraland_components/camera_mode_area.gd
- godot/src/decentraland_components/camera_mode_area.tscn
- godot/src/helpers_components/on_active_scene.gd
- godot/src/helpers_components/on_active_scene.tscn
- rust/decentraland-godot-lib/src/godot_classes/dcl_scene_node.rs
- rust/decentraland-godot-lib/src/godot_classes/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/godot_dcl_scene.rs
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
feat: new on_active_scene component that emits a signal when the scenes becames active or non-active
Fix https://github.com/decentraland/godot-explorer/issues/78
- Add the `OnActiveScene.tscn` to your scene.
- Connects the signal `on_scene_active` to your code.
- Do whatever you want, when the scene became active.
> fix: CameraModeArea limits, they only works in the active scene

- godot/src/decentraland_components/gltf_container.gd
- godot/src/decentraland_components/gltf_container.tscn
- rust/decentraland-godot-lib/src/godot_classes/dcl_gltf_container.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_scene_node.rs
- rust/decentraland-godot-lib/src/godot_classes/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/components/gltf_container.rs
- rust/decentraland-godot-lib/src/scene_runner/update_scene.rs
Follow the specification of delivering the scene loaded after the first tick (after onStart and first onUpdate).
> fix: stop processing ticks until all gltfs are different of loading state when the scene is loading (tick_number < 3)

- godot/src/logic/realm.gd
Example:
`/changerealm exodus.town`
It was not working.
Now it tries to add a `https://` if it doesn't have it.
> fix: ensure realm url starts with https:// or http://

- rust/decentraland-godot-lib/src/dcl/js/js_modules/main.js
Fix https://github.com/decentraland/godot-explorer/issues/43
> fix: avoid deno vm stop working on unhandled promises

- godot/src/logic/player/player.gd
- godot/src/ui/components/advance_settings/advance_settings.tscn
- rust/decentraland-godot-lib/src/avatars/avatar_scene.rs
- rust/decentraland-godot-lib/src/comms/communication_manager.rs
- rust/decentraland-godot-lib/src/comms/livekit.rs
- rust/decentraland-godot-lib/src/comms/ws_room.rs
Now avatar components (PlayerIdentityData, AvatarBase, AvatarEquippedData) to Player Entity. It follows the ADR 245
> fix: add avatar components to primary player 

- godot/src/logic/realm.gd
- godot/src/logic/scene_fetcher.gd
- godot/src/ui/components/chat/chat.gd
- godot/src/ui/explorer.gd
- rust/decentraland-godot-lib/src/comms/communication_manager.rs
- rust/decentraland-godot-lib/src/dcl/js/js_modules/EnvironmentApi.js
- rust/decentraland-godot-lib/src/dcl/js/js_modules/RestrictedActions.js
- rust/decentraland-godot-lib/src/dcl/js/js_modules/Runtime.js
- rust/decentraland-godot-lib/src/dcl/js/js_modules/Scene.js
- rust/decentraland-godot-lib/src/dcl/js/restricted_actions.rs
- rust/decentraland-godot-lib/src/dcl/js/runtime.rs
- rust/decentraland-godot-lib/src/dcl/mod.rs
- rust/decentraland-godot-lib/src/dcl/scene_apis.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_global.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_realm.rs
- rust/decentraland-godot-lib/src/scene_runner/godot_dcl_scene.rs
- rust/decentraland-godot-lib/src/scene_runner/rpc_calls/handle_restricted_actions.rs
- rust/decentraland-godot-lib/src/scene_runner/rpc_calls/handle_runtime.rs
- rust/decentraland-godot-lib/src/scene_runner/rpc_calls/mod.rs
> feat: sdk7 apis

- .github/workflows/ci.yml
- .gitignore
- godot/src/global.gd
- godot/src/logic/content/content_thread_pool.gd
- godot/src/logic/player/player.gd
- godot/src/test/testing_api.gd
- rust/decentraland-godot-lib/src/av/audio_context.rs
- rust/decentraland-godot-lib/src/av/stream_processor.rs
- rust/decentraland-godot-lib/src/av/video_context.rs
- rust/decentraland-godot-lib/src/av/video_stream.rs
- rust/decentraland-godot-lib/src/dcl/js/js_modules/Testing.js
- rust/decentraland-godot-lib/src/dcl/js/js_modules/main.js
- rust/decentraland-godot-lib/src/dcl/js/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/components/video_player.rs
- rust/decentraland-godot-lib/src/scene_runner/godot_dcl_scene.rs
- rust/decentraland-godot-lib/src/scene_runner/rpc_calls/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/scene.rs
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
- rust/xtask/src/main.rs
- parenting camera entity
- ensure test finished after the plan is received 
- js runtime support async while evaluating the scene code 
- typo avatar_look_at
- implement video events
> implement video events and some fixes

- godot/src/tool/avatar_renderer/avatar_renderer_standalone.tscn
When using `--avatar-renderer`, the BG was black. Now it's transparent.
> fix: use transparent background for avatar renderer export images

- godot/src/decentraland_components/gltf_container.gd
- rust/decentraland-godot-lib/src/content/content_provider.rs
- rust/decentraland-godot-lib/src/content/gltf.rs
- rust/decentraland-godot-lib/src/scene_runner/tokio_runtime.rs
- limit to 1 thread for content loading
- fix shared animation resource set loop property to all the instances
Note, the non-shared animation resources increases the memory consuming:
```
- without duplicating animations: 120.3MB to 153.3MB
- with duplicating animations: 120.3MB to 168.0MB
```
Fixes https://github.com/decentraland/godot-explorer/issues/162 and https://github.com/decentraland/godot-explorer/issues/161
> fix: crashes with content loading 

- rust/decentraland-godot-lib/src/dcl/js/js_modules/EthereumController.js
Now it matches as Foundation client works
> fix: sendAsync format the response as jsonRPC

- .github/workflows/android-build.yml
- godot/src/test/testing_api.gd
- godot/src/ui/components/pointer_tooltip/tooltip_label.gd
- rust/decentraland-godot-lib/src/auth/dcl_player_identity.rs
- rust/decentraland-godot-lib/src/av/video_context.rs
- rust/decentraland-godot-lib/src/content/audio.rs
- rust/decentraland-godot-lib/src/content/bytes.rs
- rust/decentraland-godot-lib/src/content/content_notificator.rs
- rust/decentraland-godot-lib/src/content/content_provider.rs
- rust/decentraland-godot-lib/src/content/download.rs
- rust/decentraland-godot-lib/src/content/gltf.rs
- rust/decentraland-godot-lib/src/content/mod.rs
- rust/decentraland-godot-lib/src/content/texture.rs
- rust/decentraland-godot-lib/src/content/thread_safety.rs
- rust/decentraland-godot-lib/src/content/video.rs
- rust/decentraland-godot-lib/src/content/wearable_entities.rs
- rust/decentraland-godot-lib/src/dcl/js/engine.rs
- rust/decentraland-godot-lib/src/dcl/js/js_modules/CommunicationsController.js
- rust/decentraland-godot-lib/src/dcl/js/js_modules/utils.js
- rust/decentraland-godot-lib/src/dcl/js/mod.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_ui_background.rs
- rust/decentraland-godot-lib/src/http_request/http_queue_requester.rs
- rust/decentraland-godot-lib/src/scene_runner/components/ui/scene_ui.rs
Avoid duplicating to load the same resource more than once, with `ContentNotificator` applied to the downloads all the shared dependencies awaits the first request.
Use `tokio::fs` instead of `godot::FileAccess` (crashing when multiple file handlers in the same file)
- feat: add content notification to hold futures of downloads 
- fix: move to std::fs/tokio::fs instead of godot FileAccess
- fix: now it waits until promises are resolved before take snapshot
- fix: tooltip when action=any
- chore: move PackedByteArray conversion from Vec to a bytes module  
- fix: race condition when `getUserData` is called after `onStart` but it's not resolved by the `async` engine
- chore: remove nop()
- mock ~system/CommunicationsController::sendBinary
- fix: remove error message when texture loading …
> fix: content loading related crashes (android)

- rust/decentraland-godot-lib/src/dcl/js/js_modules/fetch.js
- rust/decentraland-godot-lib/src/godot_classes/dcl_ui_background.rs
- rust/decentraland-godot-lib/src/scene_runner/components/ui/scene_ui.rs
- fix: ui-background not setting the region
- fix: not hiding `display:none`
- use `Headers` object in the fetch response
> fix: ui-background not setting the region rect and not hiding `display:none`

- godot/src/decentraland_components/gltf_container.gd
- godot/src/global.gd
- godot/src/logic/scene_fetcher.gd
- godot/src/ui/components/loading_screen/loading_screen.gd
- godot/src/ui/components/loading_screen/loading_screen.tscn
- godot/src/ui/components/loading_screen/loading_screen_progress_logic.gd
- godot/src/ui/components/pointer_tooltip/tooltip_label.gd
- godot/src/ui/explorer.gd
- rust/decentraland-godot-lib/src/content/content_provider.rs
- rust/decentraland-godot-lib/src/godot_classes/dcl_scene_node.rs
- rust/decentraland-godot-lib/src/scene_runner/update_scene.rs
Fix #186 
It was required: https://github.com/decentraland/sdk7-adaption-layer/commit/f3a47d74562366427d014162831923d13ad71839
- feat: add more loading steps in functions of gltf loaded
- chore: `--preview` cmd arg enables the debug panel
- chore: increase parallel downloads from 4 to 6
- fix: include `tick_number=3` in the pending loading state
- fix: gltf_loading gets stuck when failing
- fix: loading timeout popup colors
- fix: false-positive when only empty parcels is detected
- fix: trying to get input state of `any`
> feat: implement spawn points and fixes

- godot/assets/themes/theme.tres
- godot/src/ui/components/auth/lobby.gd
- godot/src/ui/components/auth/lobby.tscn
- godot/src/ui/components/backpack/backpack.tscn
Fix https://github.com/decentraland/godot-explorer/issues/272
https://github.com/decentraland/godot-explorer/assets/12563266/c3f0326a-08ab-4235-a9f3-2c14f2a5dfe5
Known issue:
The website is not working on Mobile.
https://decentraland.org/terms/
https://decentraland.org/privacy/
> feat: require to accept terms and privacy policy to deploy a new profile

- rust/decentraland-godot-lib/src/comms/adapter/adapter_trait.rs
- rust/decentraland-godot-lib/src/comms/adapter/livekit.rs
- rust/decentraland-godot-lib/src/comms/adapter/ws_room.rs
- rust/decentraland-godot-lib/src/comms/communication_manager.rs
- rust/decentraland-godot-lib/src/dcl/js/comms.rs
- rust/decentraland-godot-lib/src/dcl/js/engine.rs
- rust/decentraland-godot-lib/src/dcl/js/events.rs
- rust/decentraland-godot-lib/src/dcl/js/js_modules/CommunicationsController.js
- rust/decentraland-godot-lib/src/dcl/js/mod.rs
- rust/decentraland-godot-lib/src/dcl/mod.rs
- rust/decentraland-godot-lib/src/dcl/scene_apis.rs
- rust/decentraland-godot-lib/src/scene_runner/rpc_calls/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
- rust/decentraland-godot-lib/src/scene_runner/update_scene.rs
Fix #264 
- Implement `send` and `sendBinary`
- Also add `sceneStart` observable emit
1 Open the godot client and a second client (it might be the Foundation client)
2. Use `/changerealm https://leanmendoza.github.io/mannakia-dcl-scene/mannakia-dcl-scene` in both and wait until it's fully connected
3. After some seconds you have to see al the counter > 0 (in both clients)
> feat: implement `send` and `sendBinary` over comms

- README.md
Noticed a minor typo while reading over the document.
> docs: fix minor typo and grammar error in README.

- godot/src/decentraland_components/avatar_attach.gd
- godot/src/decentraland_components/player_collider_filter.gd
- godot/src/ui/components/loading_screen/loading_screen.tscn
- rust/decentraland-godot-lib/src/content/gltf.rs
- rust/decentraland-godot-lib/src/dcl/js/mod.rs
Fix #270 
As said in https://adr.decentraland.org/adr/ADR-215:
> https://adr.decentraland.org/adr/ADR-215
Colliders inside `Skeleton3D` are not supported
Also:
- fix: log long message can break the debug panel
> fix: skinned colliders not work

- rust/decentraland-godot-lib/src/dcl/js/js_modules/ws.js
- rust/decentraland-godot-lib/src/dcl/js/websocket/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/components/ui/scene_ui.rs
Add `ArrayBuffer` and `Array` support to `WebSocket::send` method.
Fix entering the world: `https://worlds.dcl-iwb.co/world/BuilderWorld.dcl.eth/`
> fix: websocket doest not support `ArrayBuffer` and `Array` of numbers

- godot/assets/avatar/mask_material.gdshader
- godot/project.godot
- godot/src/decentraland_components/avatar/avatar.gd
- godot/src/decentraland_components/avatar/wearables/wearables.gd
- godot/src/test/avatar/avatar_list.json
- godot/src/test/avatar/avatar_tester_standalone.gd
- godot/src/test/avatar/avatar_tester_standalone.tscn
- rust/decentraland-godot-lib/src/avatars/avatar_type.rs
- rust/decentraland-godot-lib/src/avatars/item.rs
- rust/decentraland-godot-lib/src/comms/profile.rs
- rust/decentraland-godot-lib/src/content/content_provider.rs
- rust/decentraland-godot-lib/src/dcl/common/wearable.rs
Fix #301 
- feat: Add `forceRender` property
- fix: Make `name` optional, some wearables fail when loading because the deserializer couldn't find the property
- chore: move wearable vlidation to rust
- make `get_wearable_representation` body_shape_id param case insensitive
- fix: hidings not working well
> fix: avatar loading issues

- godot/src/decentraland_components/avatar/avatar_emote_controller.gd
- godot/src/logic/scene_fetcher.gd
- rust/decentraland-godot-lib/Cargo.toml
- rust/decentraland-godot-lib/src/avatars/item.rs
- rust/decentraland-godot-lib/src/comms/adapter/livekit.rs
- rust/decentraland-godot-lib/src/dcl/common/mod.rs
- rust/decentraland-godot-lib/src/dcl/js/comms.rs
- rust/decentraland-godot-lib/src/dcl/js/events.rs
- rust/decentraland-godot-lib/src/dcl/js/inspector.rs
- rust/decentraland-godot-lib/src/dcl/js/mod.rs
- rust/decentraland-godot-lib/src/dcl/mod.rs
- rust/decentraland-godot-lib/src/dcl/scene_apis.rs
- rust/decentraland-godot-lib/src/scene_runner/components/ui/scene_ui.rs
- rust/decentraland-godot-lib/src/scene_runner/rpc_calls/mod.rs
- rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs
- fix: comms sender blocks the javascript runtime
- fix: ui_canvas_information is only sent when there is UI stuffs
- feat: add v8-inspector support (with feature `enable_inspector`, no default)
- feat: run scene-code without wrapping it with `require`
- fix: idle_anim is shared between avatars
- chore: remove some logs
> fix: comms sender blocks the javascript runtime

- godot/src/decentraland_components/audio_source.gd
- godot/src/logic/scene_fetcher.gd
- godot/src/ui/explorer.gd
- rust/decentraland-godot-lib/src/godot_classes/dcl_audio_source.rs
- rust/decentraland-godot-lib/src/scene_runner/components/audio_source.rs
- rust/decentraland-godot-lib/src/scene_runner/components/material.rs
- rust/decentraland-godot-lib/src/scene_runner/components/tween.rs
- rust/decentraland-godot-lib/src/scene_runner/rpc_calls/handle_restricted_actions.rs
this effect is evident in the switchable-platform scene, when you press the button and the platform goes instantaneously to the end
also:
- feat: update last audio source spec
- fix: some mesh renderer disappear because the depth-test (material)
- fix: with scene-radius==0 when changing parcel position, it shows the loading screen and call moveTo
> fix: tween doesn't use the duration so it fallbacks to 0 and finishes immediately

- Dockerfile
- rust/decentraland-godot-lib/src/scene_runner/components/transform_and_parent.rs
- Fix infinity loop finding an entity
- workaround: CI builds on 22.04, so the Dockerfile should be 22.04 
Future:
A. The ffmpeg should be included in the Dockerfile instead of installing the from `apt`.
B. Build it statically
> fix: infinite loop when self-parenting

- godot/.godot/global_script_class_cache.cfg
- godot/addons/resource_tracker/plugin.cfg
- godot/addons/resource_tracker/resource_tracker_debugger.gd
- godot/addons/resource_tracker/resource_tracker_panel.gd
- godot/addons/resource_tracker/resource_tracker_panel.tscn
- godot/addons/resource_tracker/resource_tracker_plugin.gd
- godot/project.godot
- godot/src/decentraland_components/avatar/avatar.tscn
- godot/src/ui/components/loading_screen/loading_screen.gd
- godot/src/ui/components/loading_screen/loading_screen.tscn
- godot/src/ui/components/loading_screen/loading_screen_progress_logic.gd
- lib/Cargo.toml
- lib/src/content/content_provider.rs
- lib/src/content/gltf.rs
- lib/src/content/mod.rs
- lib/src/content/resource_download_tracking.rs
- lib/src/content/resource_provider.rs
- lib/src/content/video.rs
- lib/src/dcl/js/adaptation_layer_helper.rs
- lib/src/godot_classes/dcl_resource_tracker.rs
- lib/src/godot_classes/mod.rs
- lib/src/godot_classes/rpc_sender/take_and_compare_snapshot_response.rs
- src/main.rs
- src/run.rs
Add `-t` for compiling with `resource tracking`
example `cargo run -- run -et`
> feat: resource tracking and loading state ux

- godot/src/decentraland_components/gltf_container.gd
- godot/src/ui/components/map_shader/map.gdshader
- godot/src/ui/components/map_shader/map_shader.gd
- lib/src/godot_classes/animator_controller.rs
- lib/src/godot_classes/dcl_gltf_container.rs
- lib/src/scene_runner/components/animator.rs
- fix: animations not working
- chore: remove redundancy from the map.shader
> fix: animations inconsistency while fetching child_index 0 instead of actual gltf node

- godot/src/logic/scene_fetcher.gd
- lib/Cargo.toml
- lib/src/dcl/common/scene.rs
- lib/src/godot_classes/dcl_ui_text.rs
- lib/src/scene_runner/components/raycast.rs
- lib/src/scene_runner/components/ui/scene_ui.rs
- lib/src/scene_runner/components/ui/ui_text.rs
- src/copy_files.rs
> fix: raycast and uitext size computing

- lib/src/godot_classes/dcl_ui_text.rs
- lib/src/scene_runner/components/audio_stream.rs
- lib/src/scene_runner/components/ui/scene_ui.rs
- lib/src/scene_runner/components/video_player.rs
- fix blocking send while processing the scene messages
- fix ui text, skipping tags
> fix: blocking send and ui text tags

- lib/src/content/texture.rs
- lib/src/scene_runner/components/transform_and_parent.rs
Fix crashes on https://worlds.dcl-iwb.co/world/BuilderWorld.dcl.eth/
> fix: crashes in empty data textures and infinite rotations

- godot/src/decentraland_components/avatar/avatar.gd
- godot/src/global.gd
- godot/src/logic/realm.gd
- godot/src/logic/scene_fetcher.gd
- godot/src/ui/color_picker/colorable_square.gd
- godot/src/ui/components/auth/lobby.gd
- godot/src/ui/components/backpack/backpack.gd
- godot/src/ui/components/backpack/backpack.tscn
- godot/src/ui/components/custom_slider/custom_background_slider.gd
- godot/src/ui/components/wearable_button/wearable_filter_button.gd
Icon generation was not working after 4.3 update.
The issue was with the AvatarPreview duplication.
I bit of research found that the issue was due to the following: https://github.com/godotengine/godot/pull/87387
So I changed the code not to use duplication of the AvatarPreview. It just loads a parallel node.
> fix: avatar icon generation

- godot/src/logic/player/player.gd
Closes #593 
Avatar walk/jog/run animations will depend on actual velocity instead of on player's input
> fix: Avatar animations dependent on actual velocity

- lib/Cargo.toml
- src/install_dependency.rs
Fix the build system to build correctly to android from windows, removing unmask requirement.
> fix: android build on windows
